### Get all todos
GET {{host}}/api/v1/todos

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Add todo
POST {{host}}/api/v1/todos
Content-Type: application/json
Authorization: {{token}}

{
  "title": "Setup spring app for HTTP Client Demo"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.id === 1, "Response body id is not 1");
    });
%}

### Update todo
PUT {{host}}/api/v1/todos
Content-Type: application/json
Authorization: {{token}}

{
  "id": 1,
  "title": "Setup spring app for HTTP Client Demo",
  "completed": true
}
